package main

import (
	_ "github.com/Youknow2509/discord_webhook/cmd/swag/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/Youknow2509/discord_webhook/internal/global"
	"github.com/Youknow2509/discord_webhook/internal/initialize"
	"github.com/swaggo/files"       // swagger embed files
	"github.com/swaggo/gin-swagger" // gin-swagger middleware
)

// @title           API Documentation Discord Webhook
// @version         1.0.0
// @description     This is a sample server for Discord Webhook.
// @termsOfService  github.com/Youknow2509/discord_webhook/

// @contact.name   TEAM V
// @contact.url    github.com/Youknow2509/discord_webhook/
// @contact.email  lytranvinh.work@gmail.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/
func main() {
	r := initialize.Run()

	// use swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":" + global.SERVER_PORT)
}
